# pull official base image
FROM node:16.15.0

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY postcss.config.js ./
COPY tailwind.config.js ./
RUN npm install --silent
RUN npm install react-scripts@latest -g --silent

# add app
COPY . ./

EXPOSE 3000

# start app
CMD ["npm", "start"]